
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication5;
import ij.process.*;
import ij.io.*;
import ij.gui.ImageCanvas;
import ij.util.Tools;
import java.io.*;
import java.awt.Font;
import java.awt.image.ColorModel;
import java.io.File;    // imports the ij.io.Opener class (includes functions to open images)
import java.io.IOException;
import javax.swing.JFileChooser;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import ij.ImageStack;
import ij.VirtualStack;
import java.awt.Rectangle;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;


    
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jFileChooser1 = new javax.swing.JFileChooser();
        OpenImageJBtn = new javax.swing.JButton();
        OpenISBtn = new javax.swing.JButton();
        FilePath1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        DisplayImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ImageFileDislplay = new javax.swing.JList();
        OutputBoxTitle = new javax.swing.JTextField();
        OutputBox = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Ballpic = new javax.swing.JLabel();
        BGlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OpenImageJBtn.setBackground(new java.awt.Color(255, 153, 0));
        OpenImageJBtn.setForeground(new java.awt.Color(0, 0, 0));
        OpenImageJBtn.setText("Open Image J");
        OpenImageJBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        OpenImageJBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenImageJBtnMouseClicked(evt);
            }
        });
        getContentPane().add(OpenImageJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 143, 75));

        OpenISBtn.setBackground(new java.awt.Color(255, 153, 0));
        OpenISBtn.setForeground(new java.awt.Color(0, 0, 0));
        OpenISBtn.setText("Image Sequence");
        OpenISBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenISBtnMouseClicked(evt);
            }
        });
        OpenISBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenISBtnActionPerformed(evt);
            }
        });
        getContentPane().add(OpenISBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 98, 140, 81));

        FilePath1.setBackground(new java.awt.Color(255, 204, 0));
        FilePath1.setForeground(new java.awt.Color(0, 0, 0));
        FilePath1.setOpaque(true);
        getContentPane().add(FilePath1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 110, 30));

        jButton3.setBackground(new java.awt.Color(255, 153, 0));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Browse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 184, 143, 81));

        DisplayImage.setBackground(new java.awt.Color(255, 255, 51));
        DisplayImage.setForeground(new java.awt.Color(255, 255, 51));
        DisplayImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 204, 0), null, null));
        DisplayImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisplayImageMouseClicked(evt);
            }
        });
        getContentPane().add(DisplayImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 340, 260));

        jLabel2.setFont(new java.awt.Font("Razer Header Regular", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fogarty Research");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 400, 50));

        jCheckBox1.setText("jCheckBox1");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        jCheckBox2.setText("jCheckBox1");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        jCheckBox3.setText("jCheckBox1");
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        jCheckBox4.setText("jCheckBox1");
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        jCheckBox5.setText("jCheckBox1");
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        jCheckBox6.setText("jCheckBox1");
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        jCheckBox7.setText("jCheckBox1");
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        jCheckBox8.setText("jCheckBox1");
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        jCheckBox9.setText("jCheckBox1");
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        jButton1.setText("Run");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 60, 80));

        jButton4.setBackground(new java.awt.Color(255, 153, 0));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 143, 80));

        jButton5.setBackground(new java.awt.Color(255, 153, 0));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 356, 143, 80));

        ImageFileDislplay.setBackground(new java.awt.Color(255, 204, 0));
        ImageFileDislplay.setForeground(new java.awt.Color(0, 0, 0));
        ImageFileDislplay.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(ImageFileDislplay);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 110, 330));

        OutputBoxTitle.setText("Output Box");
        OutputBoxTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputBoxTitleActionPerformed(evt);
            }
        });
        getContentPane().add(OutputBoxTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 240, 30));

        OutputBox.setBackground(new java.awt.Color(255, 153, 0));

        jTextArea1.setBackground(new java.awt.Color(255, 153, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        OutputBox.setViewportView(jTextArea1);

        getContentPane().add(OutputBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 240, 430));

        Ballpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication5/flashing_spiky_ball_greenedited2.png"))); // NOI18N
        Ballpic.setMaximumSize(new java.awt.Dimension(24, 25));
        getContentPane().add(Ballpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 220, 90));

        BGlbl.setBackground(new java.awt.Color(0, 0, 0));
        BGlbl.setOpaque(true);
        getContentPane().add(BGlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 570));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText(":D");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OutputBoxTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutputBoxTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OutputBoxTitleActionPerformed

    private void OpenImageJBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenImageJBtnMouseClicked
        // TODO add your handling code here:
        try {
            Process p = Runtime.getRuntime().exec("C:/Program Files/ImageJ/ImageJ.exe");
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }//GEN-LAST:event_OpenImageJBtnMouseClicked

    private void OpenISBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenISBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OpenISBtnMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int o=jFileChooser1.showOpenDialog(this);
        if(o==JFileChooser.APPROVE_OPTION){
            File f=jFileChooser1.getSelectedFile();
            DisplayImage.setIcon(new ImageIcon(""+f));
        }
        
       
    }//GEN-LAST:event_jButton3ActionPerformed
 
    private void OpenISBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenISBtnActionPerformed
        // TODO add your handling code here:
        

        //int o= new ij.plugin.StackMaker*** find out how to import pluggins 
        //int o=jFileChooser1.showOpenDialog(this);
        // if(o==JFileChooser.APPROVE_OPTION){
        //    File f=jFileChooser1.getSelectedFile();
        //     DisplayImage.setIcon(new ImageIcon(""+f));
        // } This is all for Image Sequence Opening
    }//GEN-LAST:event_OpenISBtnActionPerformed

    private void DisplayImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayImageMouseClicked
        // TODO add your handling code here:
        //Have this pop out into a larger window
    }//GEN-LAST:event_DisplayImageMouseClicked
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGlbl;
    private javax.swing.JLabel Ballpic;
    private javax.swing.JLabel DisplayImage;
    private javax.swing.JLabel FilePath1;
    private javax.swing.JList ImageFileDislplay;
    private javax.swing.JButton OpenISBtn;
    private javax.swing.JButton OpenImageJBtn;
    private javax.swing.JScrollPane OutputBox;
    private javax.swing.JTextField OutputBoxTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
